In [1]:
%matplotlib notebook

In [2]:
import numpy as np

In [3]:
sky = [0, 1, 0]

In [12]:
def normalize(v):
    l = np.linalg.norm(v)
    if l == 0:
        return None
    return v/l

In [4]:
direction = [-10, 3, 4]

In [8]:
left = np.cross(sky, direction)
left = left / np.linalg.norm(left)

In [5]:
a = np.dot(sky, direction) / np.linalg.norm(sky) /np.linalg.norm(direction)

In [25]:
SRC = np.matrix([left, sky, normalize(direction)]) 
DST = np.matrix([[1, 0, 0], [0, np.cos(a), -np.sin(a)], [0, 0, 1]]).transpose()

In [16]:
DST * DST.transpose()

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        , -0.26511979],
        [ 0.        , -0.26511979,  1.        ]])

In [17]:
SRC * SRC.transpose()

matrix([[  1.00000000e+00,   0.00000000e+00,   5.55111512e-17],
        [  0.00000000e+00,   1.00000000e+00,   2.68328157e-01],
        [  5.55111512e-17,   2.68328157e-01,   1.00000000e+00]])

In [31]:
np.matmul(np.matmul(DST, np.linalg.inv(SRC)), normalize(direction))

matrix([[-0.60761429,  0.25872616, -0.79142095]])

In [33]:
DST

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.96421548,  0.        ],
        [ 0.        , -0.26511979,  1.        ]])

In [32]:
normalize(direction)

array([-0.89442719,  0.26832816,  0.35777088])