In [1]:
import numpy as np

In [113]:
ranks = [3, 5, 2]

In [114]:
def dihedral_angle_to_geodesics(A, B, C):
    return np.arccos(np.cos(C)/(np.cos(A)*np.cos(B)+np.sin(A)*np.sin(B)))

def dihedral_triangle_to_geodesics(A, B, C):
    return [dihedral_angle_to_geodesics(A, B, C),
            dihedral_angle_to_geodesics(B, C, A),
            dihedral_angle_to_geodesics(C, A, B)]

In [115]:
from numpy import linalg

In [116]:
def y_rotation_matrix(deg):
    return np.matrix([
            [np.cos(deg), 0, -np.sin(deg)],
            [0,           1,  0],
            [np.sin(deg), 0,  np.cos(deg)]])
def z_rotation_matrix(deg):
    return np.matrix([
            [np.cos(deg), -np.sin(deg), 0],
            [np.sin(deg), np.cos(deg) , 0],
            [0          , 0           , 1]])

In [117]:
dihedrals = [np.pi/rank for rank in ranks]

In [118]:
geodesics = dihedral_triangle_to_geodesics(*dihedrals)

In [119]:
geodesics

[1.5707963267948966, 0.55357435889704498, 0.36486382811348295]

In [120]:
dihedrals

[1.0471975511965976, 0.6283185307179586, 1.5707963267948966]

In [121]:
vectors

matrix([[ 0.        , -0.8660254 ,  0.40824829],
        [ 0.        ,  0.        , -0.57735027],
        [ 1.        ,  0.5       ,  0.70710678]])

In [122]:
z = np.array([[0], [0], [1]])
vectors = np.matrix([[], [], []])
for i in range(3):
    geodesic_rotator = z_rotation_matrix(np.pi - geodesics[i])
    vectors = geodesic_rotator * vectors
    dihedral_rotator = y_rotation_matrix(dihedrals[(i + 1) % 3])
    vectors = dihedral_rotator * vectors
    vectors = np.concatenate([z, vectors], axis=1)
    print(np.pi / np.arccos(np.minimum(vectors.transpose() * vectors, 1.0)))
    #print (vectors)
    #print (vectors)
    

[[ inf]]
[[ inf   2.]
 [  2.  inf]]
[[ inf   3.   5.]
 [  3.  inf   2.]
 [  5.   2.  inf]]


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:9: RuntimeWarning:

divide by zero encountered in divide



In [123]:
np.pi / np.arccos(np.minimum(vectors.transpose() * vectors, 1.0))

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: RuntimeWarning:

divide by zero encountered in divide



matrix([[ inf,   3.,   5.],
        [  3.,  inf,   2.],
        [  5.,   2.,  inf]])

In [124]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [157]:
pt = np.random.randn(3,1).transpose()
points = []
memory = {}
word = ()
for i in range(300):
    k = np.random.randint(vectors.shape[1])
    while memory.get(word) == k:
        k = np.random.randint(vectors.shape[1])
    if len(word) == 0 or word[-1] != k:
        word = word + (k,)
    memory[word] = k
    v = vectors[:, k]
    pt_v = (pt*v)
    v2 = (v.transpose()*v)
    a = np.linalg.det(pt_v/v2)
    pt = pt - v.transpose() * a * 2    
    points.append(pt)


In [145]:
points_mat = np.concatenate(points, axis=0)

In [146]:
a

0.19711669165718998

In [147]:
vectors[0,:]

matrix([[ 0.        , -0.8660254 ,  0.46708618]])

In [158]:
import plotly.plotly as py
import plotly.graph_objs as go

x, y, z = points_mat.transpose()
trace1 = go.Scatter3d(
    x=x.transpose(),
    y=y.transpose(),
    z=z.transpose(),
    mode='markers',
    marker=dict(
        size=12,
        color='rgba(217, 100, 217, 1.0)',
        line=dict(
            color='rgba(0, 217, 0, 1.0)',
            width=0.5
        ),
        opacity=0.8
    )
)
data = [trace1]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=0
    )
)
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='simple-3d-scatter')

In [135]:
np.where(np.histogramdd(np.array(points_mat), 100)[0] >
         ?/0.0)[0].shape

(82,)

In [151]:
memory.keys()[0]

(0,
 2,
 0,
 2,
 0,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 1,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 2,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 2,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 0,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 0,
 1,
 0,
 2,
 1)